name: 4th-down
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - xgboost
  - pymc3
  - arviz
  - scipy
  - theano
  - ipywidgets
  - jupyter
  - ipykernel
  - pillow
  - pip
  - pip:
    - tqdm
    - nfl-data-py
    - tabulate
    - meteomatics